### ISSUE TITLE
bot无返回信息

### ISSUE THREAD

**Issue by yukiryo** [CYDXDianXian/AI_image_gen#10]
![image](https://user-images.githubusercontent.com/58250223/195604484-6614da52-935a-417b-9f2a-3456b169e756.png)

**Comment by CYDXDianXian** [comment]
这是你hoshinobot没有部署好导致的问题，报错显示没有安装res包导致其他模块无法读取相应目录和文件。具体请参照hoshinobot的部署方法：https://github.com/Ice-Cirno/HoshinoBot

**Comment by yukiryo** [comment]
安装res后依然无效
![image](https://user-images.githubusercontent.com/58250223/195609301-6f861a26-0c23-4824-aa9a-bec3e9407e2b.png)

**Comment by CYDXDianXian** [comment]
在hoshino/config/__bot__.py文件中，MODULES_ON里添加 "AI_image_gen"
请检查是否在配置中开启了该模块

**Comment by yukiryo** [comment]
![image](https://user-images.githubusercontent.com/58250223/195610106-8bcb1c24-def5-4394-a3da-78b8d715fa10.png)

**Comment by yukiryo** [comment]
![image](https://user-images.githubusercontent.com/58250223/195612199-cd670bd6-bf54-484b-8732-7b31fbc25793.png)

**Comment by CYDXDianXian** [comment]
![image](https://user-images.githubusercontent.com/71607036/195621519-a913713e-3cfc-4d0d-9ca9-8c53f7c6c6f7.png)
你是不是目录没放对位置，你确定放在...HoshinoBot\hoshino\modules目录下了吗？仔细看下README的配置方法看看哪一步出错了

**Comment by yukiryo** [comment]
都检查过了的
![image](https://user-images.githubusercontent.com/58250223/195624692-811799ed-0691-4b38-97e3-b3979a387468.png)

**Comment by CYDXDianXian** [comment]
要不进hoshino群问问大佬们吧，这问题我一头雾水。。。

**Comment by CYDXDianXian** [comment]
我甚至按照你的相同配置情况，删了res包并只开启这四个模块尝试复现问题，但依然能正常使用。。。所以我怀疑是别处出了问题，并不是插件本身的问题。
![image](https://user-images.githubusercontent.com/71607036/195689913-fc268bb4-85d1-4f9b-8440-3782638b2850.png)
![image](https://user-images.githubusercontent.com/71607036/195690025-695945f2-eb87-438c-b877-d5f3cde86f19.png)

**Comment by tang-bai** [comment]
有没有可能是依赖没打完

> 都检查过了的 ![图像](https://user-images.githubusercontent.com/58250223/195624692-811799ed-0691-4b38-97e3-b3979a387468.png)

**Comment by SanaChitose** [comment]
有可能是nonebot版本问题，本插件需求的nonebot版本为1.8.4，但我实测1.8.4会导致hoshino出现非特定的无响应问题（包括lssv），可以试试1.8.0，测试下来并不影响插件使用

**Comment by CYDXDianXian** [comment]
> 有可能是nonebot版本问题，本插件需求的nonebot版本为1.8.4，但我实测1.8.4会导致hoshino出现非特定的无响应问题（包括lssv），可以试试1.8.0，测试下来并不影响插件使用

nonebot==1.8.4是我本地测试环境下用的版本，不应该有问题才对啊。。。

**Comment by yukiryo** [comment]
![image](https://user-images.githubusercontent.com/58250223/195764641-a96a9663-66ac-430c-ab81-0abf4754a391.png)
这个有影响吗

**Comment by yukiryo** [comment]
![image](https://user-images.githubusercontent.com/58250223/195766917-833937f9-97c9-4ff0-b37a-95d5c33a069f.png)

**Comment by SanaChitose** [comment]
建议敲一下lssv先……
