### ISSUE TITLE
之后会支持百度翻译吗

### ISSUE THREAD

**Issue by tang-bai** [CYDXDianXian/AI_image_gen#11]
目前百度在实名认证之后是有每个月的百万字符翻译额度,就算是没实名每个月也有5万字符的费用额度
![image](https://user-images.githubusercontent.com/71223830/195743597-ef3f128d-a8b1-4e13-8484-3a2f2748e6d6.png)

**Comment by CYDXDianXian** [comment]
看着挺不错，后续有时间我更新一下，主要是我感觉百度翻译的准确度比有道好多了...

**Comment by tang-bai** [comment]
有道好像收费还比百度贵2天我就用了3块钱

**Comment by CYDXDianXian** [comment]
已更新
