### ISSUE TITLE
生成失败…list index out of range

### ISSUE THREAD

**Issue by XT-G3** [CYDXDianXian/AI_image_gen#12]
问下大佬，我novelai注册了，也开通了付费服务，但是api这个地方我不太清楚应该是填什么，填了个不知道对不对，然后底下token填了注册时发给我的token，绘图的话就一直相应“生成失败…list index out of range”其他命令应该都能正常响应，大佬教教要怎么解决啊
![QQ截图20221014192659](https://user-images.githubusercontent.com/111116375/195837221-8b1550d3-8d2b-44c3-91c6-d2db0fe48885.png)
![QQ截图20221014192713](https://user-images.githubusercontent.com/111116375/195837233-41e4ba57-7f05-4bab-b4db-d44ae1c633f9.png)

**Comment by CYDXDianXian** [comment]
本插件使用的是私人搭建的第三方API接口。如果开了官网会员，建议去使用[koishijs / novelai-bot](https://github.com/koishijs/novelai-bot)这个bot。目前官网并没有现成的API可以直接拿来用的，所以都是大佬个人买了会员搭建的API。。。

**Comment by XT-G3** [comment]
好的，谢谢大佬
