### ISSUE TITLE
使用naifu绘图后报错

### ISSUE THREAD

**Issue by hupimaodaren** [CYDXDianXian/AI_image_gen#19]
使用naifu，
小号：ai绘画 1girl
bot回复：生成失败…list index out of range
naifu的cmd里面显示INFO:     127.0.0.1:59984 - "GET /got_image?tags=1girl&token= HTTP/1.1" 404 Not Found
请问如何处理呢，谢谢！

**Comment by azmiao** [comment]
额。。。你token填了吗或者验证了吗？

**Comment by tang-bai** [comment]
> 使用naifu， 小号：ai绘画 1girl bot回复：生成失败…list index out of range naifu的cmd里面显示INFO: 127.0.0.1:59984 - "GET /got_image?tags=1girl&token= HTTP/1.1" 404 Not Found 请问如何处理呢，谢谢！

你是不是api地址都没填

**Comment by hupimaodaren** [comment]
> 额。。。你token填了吗或者验证了吗？

部署在本地的话也需要token吗?

**Comment by hupimaodaren** [comment]
> > 使用naifu， 小号：ai绘画 1girl bot回复：生成失败…list index out of range naifu的cmd里面显示INFO: 127.0.0.1:59984 - "GET /got_image?tags=1girl&token= HTTP/1.1" 404 Not Found 请问如何处理呢，谢谢！
> 
> 你是不是api地址都没填

填的是naifu本地的地址127.0.0.1:6969，
群里面使用tag为1girl，在cmd里面能看到naifu收到 "GET /got_image?tags=1girl&token= HTTP/1.1" 404 Not Found
在web端同样输入1girl，在cmd里面能看到naifu收到 "GET /predict-tags?prompt=1girl HTTP/1.1" 200 OK

**Comment by tang-bai** [comment]
这个项目好像不支持本地部署,如果是本地部署的可以转到https://github.com/koishijs/novelai-bot
这个项目

**Comment by hupimaodaren** [comment]
> 这个项目好像不支持本地部署,如果是本地部署的可以转到https://github.com/koishijs/novelai-bot 这个项目

辛苦您回复了，谢谢

**Comment by azmiao** [comment]
确实，本地的不行，所以我现在不用本地了，还能省资源（
