### ISSUE TITLE
成功trigger，但是没有出图

### ISSUE THREAD

**Issue by SanaChitose** [CYDXDianXian/AI_image_gen#2]
使用的是路路佬的api和token，提示信息正常，但是等了很久也没有出图，是api响应问题吗？
![图片](https://user-images.githubusercontent.com/102790983/195229696-1c43abfd-a7ce-42ae-9012-ae4c9455e944.png)
![图片](https://user-images.githubusercontent.com/102790983/195229716-87609833-68c5-4fcd-9250-2db462ef32ad.png)
![图片](https://user-images.githubusercontent.com/102790983/195229772-5e303b2d-872d-4969-a887-569f40fa1fdf.png)

**Comment by SanaChitose** [comment]
应该也不是风控原因，因为day limit没有变化
![图片](https://user-images.githubusercontent.com/102790983/195229904-6f67df00-4cec-402f-8ef1-7f1284439f25.png)

**Comment by SanaChitose** [comment]
大概15分钟后出回复了……
![图片](https://user-images.githubusercontent.com/102790983/195231638-1d88a9fd-3de2-4d38-9b5a-3aeec531d487.png)
感觉确实像是生成成功率的问题

**Comment by CYDXDianXian** [comment]
我这边暂时还没遇到过这种问题，估计是网络不稳定导致的吧...

**Comment by CYDXDianXian** [comment]
对了，token填对没有，获取的token需要进群验证一下才能使用

**Comment by SanaChitose** [comment]
> 对了，token填对没有，获取的token需要进群验证一下才能使用

token验证过，昨天发现全局代理可以出图，应该是网络问题
