### ISSUE TITLE
ai绘图功能报错卡死

### ISSUE THREAD

**Issue by Ning-Off** [CYDXDianXian/AI_image_gen#23]
![image](https://user-images.githubusercontent.com/102615856/196660299-40fd959b-78f4-4096-84b5-08b2d9aac615.png)
严重bug，ai绘图调用卡死

**Comment by Ning-Off** [comment]
调用AI绘图后再次调用AI绘图功能会被honshion忽略，但若在进行第一次AI绘图完毕后使用其他功能后再次使用AI绘图则可以使用。

**Comment by SonderXiaoming** [comment]
同样的问题（怎么会卡死的）

**Comment by CYDXDianXian** [comment]
尝试修复了一下：[以防出现奇怪的报错，还是用这种方法吧](https://github.com/CYDXDianXian/AI_image_gen/commit/e4013e0435587690cee12974f79d929a8179e7f2)
我也只遇到过一次，所以根据当时的报错信息来改的。。

**Comment by Ning-Off** [comment]
更新以后问题解决了，暂时没有发现其他的大bug（小bug都没发现捏），电线大佬NB

**Comment by Ning-Off** [comment]
谢谢大佬

**Comment by Ning-Off** [comment]
1

**Comment by Ning-Off** [comment]
th
