### ISSUE TITLE
20号版本更新之后查看群图片报错

### ISSUE THREAD

**Issue by along411** [CYDXDianXian/AI_image_gen#27]
貌似是查看本群图片功能没能指到res那边，我沿老版本目录换了一下SaveImage还可以接着用

**Comment by CYDXDianXian** [comment]
res/img/AI_sutu和SaveImage目录都得保留，旧图片在数据库中的路径指向在SaveImage目录，更新后新上传的图片路径指向都在res/img/AI_sutu目录
