### ISSUE TITLE
今天从拉了一边 就这样了 大佬求帮助

### ISSUE THREAD

**Issue by zhp3635** [CYDXDianXian/AI_image_gen#3]
![image](https://user-images.githubusercontent.com/115550164/195230020-ff2d8f6b-97aa-4a80-a419-1c852190d88e.png)

**Comment by SanaChitose** [comment]
改个service name就行了

**Comment by SanaChitose** [comment]
![图片](https://user-images.githubusercontent.com/102790983/195231806-a5d730e0-18ab-4b8e-bc2f-5eccb2acee1f.png)

**Comment by CYDXDianXian** [comment]
这是缺少依赖导致的，更新了之后新增了依赖pyahocorasick，重新安装一下依赖即可：
```
pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
```

**Comment by CYDXDianXian** [comment]
如果没什么问题我先关闭issues了，如还有问题可以再开~
