### ISSUE TITLE
无法访问黑白名单

### ISSUE THREAD

**Issue by yuuki-nya** [CYDXDianXian/AI_image_gen#30]
版本：49cd3a4

config.json 设置
        "whitelistmode": true,
        "blacklistmode": false,
使用指令
绘图 白名单/黑名单 添加/删除
得到的回复均是
"无法访问黑白名单"
但实际写入了grouplist.json
如果重复添加群也会写入list，但会导致白名单功能整个失效，所有群都不算进白名单。

**Comment by CYDXDianXian** [comment]
感谢反馈！已解决，请拉取更新~
