### ISSUE TITLE
『查看全部(个人)图片』报错

### ISSUE THREAD

**Issue by WindStill** [CYDXDianXian/AI_image_gen#31]
可能是nonebot版本的问题，我这里的MessageSegment不能自动转换成字符串。

大佬看看能不能兼容下老版本的nonebot（我是docker容器，一升级nonebot，容器就挂了），改成原来的：
`resultmes = f"[CQ:image,file={imgmes}]"`

![image](https://user-images.githubusercontent.com/958456/197924172-165ffc12-7489-4f2e-bb92-5ac83377db89.png)

![image](https://user-images.githubusercontent.com/958456/197925387-53c795de-4ef1-4a01-af56-f1d9aff97aac.png)

**Comment by CYDXDianXian** [comment]
那你的其它功能能用吗？我全都使用MessageSegment方法来构造CQ码的，ai绘图、图片鉴赏、图片超分等等都是这么写的，还是说只有你这边只有这个功能出了问题？

**Comment by CYDXDianXian** [comment]
感谢反馈，已修复
