### ISSUE TITLE
bot没返回消息

### ISSUE THREAD

**Issue by McAZero** [CYDXDianXian/AI_image_gen#33]
其他指令可以用，绘图相关指令用不了
![image](https://user-images.githubusercontent.com/52328924/198119276-b0a7143d-2de8-41cd-8934-46aebd3ccc62.png)
![image](https://user-images.githubusercontent.com/52328924/198119291-a0dc0163-77b4-496b-9921-6cfb08eba8ed.png)
![image](https://user-images.githubusercontent.com/52328924/198119532-d7d19a70-9173-4631-ad66-c96b8ea68e70.png)
![image](https://user-images.githubusercontent.com/52328924/198119592-a3213372-27e1-4a1f-b0ea-4d5af7220084.png)
![image](https://user-images.githubusercontent.com/52328924/198125610-06188747-41c9-44da-962d-19c62deafbf0.png)

**Comment by CYDXDianXian** [comment]
发送lssv看看ai绘图服务是否已开启
然后记得再重新复制一下配置文件，更新了api

**Comment by McAZero** [comment]
> 发送lssv看看ai绘图服务是否已开启

莫得反应

**Comment by CYDXDianXian** [comment]
bot.py里把超级用户QQ号设为自己的号，再去敲lssv

**Comment by McAZero** [comment]
> bot.py里把超级用户QQ号设为自己的号，再去敲lssv
设置了，还是莫得反应qwq
![image](https://user-images.githubusercontent.com/52328924/198139409-57c11901-f31e-4a6b-b78c-97a19943d99d.png)
![image](https://user-images.githubusercontent.com/52328924/198139483-e7caed3a-aec3-48cd-854d-100c7811b64e.png)

**Comment by CYDXDianXian** [comment]
同样的问题可以看看 #10 ，这种问题大概率就是bot部署不规范导致的

**Comment by int-PP** [comment]
没装依赖？
