### ISSUE TITLE
使用大部分功能会有如下报错

### ISSUE THREAD

**Issue by KeitP** [CYDXDianXian/AI_image_gen#35]
ai绘图、清晰术、识图等等功能都有这样的报错。
分别是mirai的报错信息和hoshino的报错信息。
![{2BOU 5RNN9G WMK)5Z47@K](https://user-images.githubusercontent.com/96611212/199730477-d5780685-1580-49d1-8331-3a49ff82b10e.png)
![G34X WBEG9)Q1ZOF$ G5CGS](https://user-images.githubusercontent.com/96611212/199730507-5e0524d2-bfd5-4908-a242-a9dd3e091871.png)

**Comment by CYDXDianXian** [comment]
这个是go-cqhttp版本太低导致的，更新到最新版就好了
