### ISSUE TITLE
生成的时候报错：生成失败…list index out of range

### ISSUE THREAD

**Issue by Jacky117** [CYDXDianXian/AI_image_gen#5]
能正常triggered，但生成的时候出现报错信息
![22](https://user-images.githubusercontent.com/107171157/195312384-b9ea1fd6-fc0f-4689-ad4e-f8bf48bc74c5.png)

**Comment by CYDXDianXian** [comment]
![image](https://user-images.githubusercontent.com/71607036/195314831-16ac3c0c-4a1f-43d8-b0b2-12a60696c10a.png)
奇怪，我这边测试是正常的。。。估计是配置文件缺少对应的key所致，吧config.json里的api和token备份一下，然后删掉config.json，重新从仓库拉取更新，或者重新克隆仓库试试。

**Comment by Jacky117** [comment]
重新克隆了仓库，拉取了更新，还是出现了上述同样的问题，暂时不清楚什么原因，这个报错指向了list可能越界的问题，但代码应该不会有问题才对

**Comment by CYDXDianXian** [comment]
你用 traceback.print_exc() 输出一下详细报错信息到控制台，我看一下，类似这样
```
...
except Exception as e:
        traceback.print_exc()
        await bot.send(ev, f"报错:{e}",at_sender=True)
```

**Comment by Jacky117** [comment]
在“ai绘图”和“以图绘图”这两个指令的代码段添加traceback.print_exc() 后发现机器人无响应（可能是程序运行出错？），但发现在“上传图片”这个指令的代码部分有这条处理异常的代码，这是该指令下的报错信息
![333](https://user-images.githubusercontent.com/107171157/195332949-03b15ad0-0f0a-4276-ae45-1fb52870c7f2.jpg)

**Comment by joeyHXD** [comment]
我也遇到了一样的问题，把try except 删了后是这行出问题
line 481, in gen_pic
    load_data = json.loads(re.findall('{"steps".+?}', str(image))[0])
IndexError: list index out of range

**Comment by joeyHXD** [comment]
print(str(image)) 出来是这样的，findall就成空的了

b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x01\x90\x00\x00\x00\x1a\x08\x02\x00\x00\x00\x16\x81\x9d\x91\x00\x00\x08\x8bIDATx\x01\xed];v\x1b\xb9\x12m\xcd\x99\xa5H\x0e|\xbc\x02j\x05\xb2\x13G^\x02\x15J\x893\x87\xce&\xa1Bi\t\x139\x19j\x05\xd6\n|\x1cH\xda\x8b\x06@\xa1~@5\x80&\xd9\x1c\x92\x03\x07">U\xb7n]\xa0\xd1ht\xcf{goooC\xff\xd7\x15\xe8\nt\x05\x8eA\x81?\x8e\x81d\xe7\xd8\x15\xe8\nt\x05\xbc\x02}\xc1\xea\xf3\xa0+\xd0\x158\x1a\x05\x8e`\xc1z\xbc>s\xff\xae\x1f\xe7\xd1t^\xf4\xed8\x07n\x97w\xaf\xdb\xa1t\xef\xffB\x81C\x9eW\x1b\xe9\xf1zw\xe9.\xc3l6B\x9es^\xa1\x9a\xed\x11,X\x9ap\xafu\x05fU\xe0\xe4V\x9a\xf9\xd4\xf2k\xd8\xc7\x87\xf9\xf0-\xe4\x13Y\xb0\xc2,\x9bk\x13f\xe9\xd6\xdbNT\x81\xc7\x1f\xee\n\\\xac\xbe^\x85\xfc\xfa\xbc\xa2a>\xbf\xf9\xe9^\xd0\xfd\xbc9\xa7\x96\xd7\x7f\xfe~r\x95\xe5\xda\xb5\xbb\x7f\xf7 \x19u\xcfS8\x8d\x05\xeb\xf5\xf9\xd7<\xf2t\xd4\xff\x97\x02\xafw\xdf\xfdz\xf5\xe5\x13\\\x96}^\x95\x86\xff\xe5wX\xaf>\xefe\xa1B"\xa7\xb1`a6\xfd\xb7+\xb0\x8d\x02\xb0gX~\x13\xdb\x88m\xe0\xba\xef\xee\x15h[\xb0\xc2\xce8\x9c\xb7\xc1\xd1\x9b?c\xb3\xcf\xc1\xe1\x04\x00\xfa\xf3\x13:\xc7\xbfj #\x98\x08J\x04\xb0\xbe\xb8\xf5k\xfd\xc3\xc7\x10W\x9f\x0b\xaax\xc6\xa1\xa1B\x0b\x15\xf4P8\xd88\x16\xa1I\x1c\x8a\x05h\xe1\x11V\xa5\xdb\xf2P[`\xe2\xf1U\xb71F\xe5x\xca[\t@\xdcuA9\x18\xe12J\x19\xa8BH{\x8b\x9dC!\x97B\x97N@\xd6\x1e\xff\xf2\xf3h\xe9\xb7\x0c\xe0\x7fd\xf3\n\xd4J5t\x19\xe6\x1d\x05a!u\x8f\x82"\x06DnFu\xe0\xf8\x8a\xae\xba\xbb\xf0r\xcc\x88.=\xa5\xdc\x9b\x95\xe1\xf9\xb3\xf2w\xbdt\xe0\x8b\xd5z\xb5H\x82\xe0\xf3k\xf0\x0fV\x89\x01=\xe1z\x8b\xaa\xc1K\x16\xc0\x85]\x84\xa0*\x12\xd35<\x16\xab\x17\xe87\xfa\x80\x9d\xc4\x02N\xd4\x12}\x08\xa3\x81v\x9b8L\xd9\x950\xa8!\x88\x8c\x1c\x91c:\xe4\x97HL\xdc\x11w\xb4\xdf\x10\xa4\xddY%\x00\x15\x83>\x1fi\x8c\x9a\x88\x0c\r\x00\xee5:\x05z!\x97B\x97\x91\x047I\xb9\r\x0cbf\xf4\x1d\xd4\xbc"\xa2\x98\x1a(IC]\x16\xf6\r\xd2[\xacV\xfe\xa2\x0f\xff\x02 6\xfb\xd9h(\xe0l\x00\xb7\x16\x1dIm\xf8;4\xf9Q\x8a\xc4\x06)\x93\n\xb8\x1aqCl!\x97\x082n\x80\x98\xe4!\x95\x11n9e\xf0\xd4&\x06\x1a_\xd1l\n\xacb=\xa7H.\xec1\x92\x97_\xd1\x93\x95R\xf8h\xce\xa4\xa7\\\xcfs\xc2\xc1\x8cP\xeb\n{\x0b\x193I\'\x06\x10\x16\xeb%U\x12[\xc7\x17Z8\xbcN\xc1\xd7\xca\xe1\xc4\xe8Q\x14\xdf\xb6\x8c2a\xbe\x922\xf7V\xf8\x14r)t\xe5)p\x0b\xb8\xe9t\xa1M\xb0w\xe6\x11\x9eG\xdbCD\xb6"\x15h\x89\xaey2\xe4"\xc0\xc1\x8a\x18 &G\xc2\xd0\xc2\x87\xf9\x87\x92\x95\x04\x90Ka\x05F\x12\x17\xa3\x88\xbb\x83\xc7\xce\xa1\xc1O\x00\xe5&\xce/XQ\xf4\xc0r\x9b?S\x16,\x1d5\xe6\x15\xf9BM\x90\x0f\xa4\x04\xd9\xaaA\x1ct\x1d\x04\x13N\xc4K36\xc0\x93Q`\x8fDf\xaeBI\xcc9\xefc \xbb\xd6`\x8aL\xc1\x0fk\x10\x08\xdc\x12,\xe8\xf2\x7f\xcdP\xd4NP*L\x03\x13\x0e\x80%\x03\x81\xd0\xd1\xc6\xffn\x04.\x01\xa0\xac\xc2\x8d\rht\x03\rL6\r|\x80\xb0\xe9]\xe8\xca\x19S\x8b\xa9\x80\xd18J\x1b:\xe8\n\xe0*\x94\x92\xb9` ;*\xc1\x14\x93\x02?\xac\x01QpK\xb0(\x07W\xc8\r\xa0\x05a\x1a\xe2F\x08\xf4@t\x8d\xe3[9Em\xa3\xe8\xa9\x94\xd0n\x8b\xdf\xb63,\xd8\x19~x\xc7\xaf4\x87\xe1\xfc\xdd\x87\xb8c\xf4?\xf0\xc6 >\xcf\xc6#\xac3\xf8H\xe3\xe9\xf7K\x8b\x01\xbc\x91\xa1\x174\x84}\xf5\x99\xb6\xa6\xd4V/\x8c\xa1\r\x03\xe0\xfdz\xd6\x9fc>\xdf]\xfaGr7\xdf\xf4\xdb\xd9j^H\xa5$\x0e\xda$\xbf\xe1\xb0D\xb5\x017\x10Lu\xb8J3\x13<b\xf0\xa3\xa0\xbe\x929\xff\xf4\xc5=]?\xdd^\xb8\x8e\xe4\xb4l\x02x\xcak4\x1c\x0c\xc1\xd8\tv\xb9\xb7\xca\xa7\x90K\xa1+\xe7\x8e-\xe2\xf8\n\x9b\xcc\xdfC\x9fW\x90\xfc\xf0\xf0\x03\xbf\xb3\x86\xf7\x08tYU\x85\xc5\xac\xc9\x03\x1bZ~\xcfo\xbe\xf9\x8bUD\x0fo]\xc7\xe6@\x0bdj3a\xc1Z\xbc\xbfH\xbdwY\x07)\xf5u\xbf9~\r-Y\x14\x1en\xfdq+}~3=\xee\xcc\xe24\x12\x8aG\xa9pV\x9c\xfb\xf8Oi\xe2\xfd\x13n-\xc9\xb2\x95{\x94[\xca\xe1`\x08\xc6\x10\xca\xbdc^\xdc^\xc8\xa5\xd0\xc5\xfe\xba\xa4\xbf\xbe\xd2}\xaav\xf0\xf3*Y3\xf6\xfd\xde\x13n\xb9\xb8b\xc5\xe8\xbb\xfc\xf0a\xc2\x82\xa5\x06\xce\xae\xd0\x86X\xed\xf9\xc4\x9e\xa5j`\xe3No\xbdx\x9f\xbe\x1f\xd0\x18\xc9\x02\xb3\\\xfb\xad\xab\xdb|\x18/9\x9c\xe3\xbeh\xc7\xfbw\xe1\xceP`\xe2^\xc6\xb8\r\x95\xde\xc9\xc3\xae]\xa6\x0e\xdf\xff\xc5\xfd\xbc[\xb6\xe4\x9aU\x00\x97\x10Pn\x0b\x97\xfbMh\xa9\xf1)\xe4R\xe8\xca\t$__\xe5\x06\xdcr\x04\xf3J\xae\x19#\x1b\xc7\x9a\xb0\x9c\xef\xe4\xd2\xd5W\xff\xe2\x0cV\xac\x91\xe8\x931\xa5\xc3\xae\x16,\x18\xc8\xf4AKDj4\xc0\xb5\x99=\xc3\xcd\x8f\xab\x8d%x`}\xf8\x9e\xff\x87x\x80\x97\xed\xe4\xae\xee\xc33\xb9[\xb3\xe4%<Ti7\xf2\xb1\xcc\xb2\\\xe1\x864d\xdc\x82s\x95I\xb8\xf9\xeb\x9d|A\xbb\xab{\xd8k\xc1\x90U\xc1s\xfe\xd5p\x80i\r\x81\x07k\xe9-L\'\xc5G\xe7\xd2\xdaEvSv!\xc70\xaf\xe2\x9a\xe1\xe6~\xbeq\xdc`\xa0I\xa7\xb6\x02<\x94\xfaa\xcf\xa3\xb7!\x94\xad\xd4^h\xacb\x9e\x9c\xc1\xdd\x1b\x17\xeb\xf8\xa8\xa1\xef\xf0\xce\x84\xee\xf8\xcd\x06r?\xc3;\x04\x8ccR\x8c\xd8\xca\x06]\x89\x80\xf7\x8c\x8d\xa2\rZ\xa2\'r\x14@\xd8$\\\x02\x0c\xd7\x03\x02W\x81\xa0\x82\xcd8G\x1a\xe2\xc5"\x1d\x97\xb2`\x91-!\xd7\x98DP\xe2\x8e\xf6\x84\xb8^\x12\x16k\x11\x9b\xd08\xb5Pu\x95G5\x1c\xa9M\x04\xbc\x7f\xf6\x1e\xd0\xee\xad\xf1)\xe4R\xe8R\t`\xa50T\x91\x05I\xea]p\xec\x942\xb1Q\xb4)T\xccF\x00a\x93p\xd9~^aJ\x00\x0e\x1f\x04\xa9\x00\xe64K\xe2Fg|\xe5\x9d`\x8af\x95"\x9a\xf9\xdf\xd0aF\x97V\x9b\x95\'\xbc%L2\x8f#\xc7c\x80C\xa0\x17H\xe1\xb5\x99\xc1r\x19\x0e\xdd9\x8e\x95h\x9c0!4E\xb4\xe3\xa9U\x02\xe7\x1f\xa3G$\x02\xe1!\x1e\xcb\x0b\x86G\x0c\xa4\'\x080\x04\x9b\xd8\xc4\xdeU\xfe\xd9\x99\x88\x8b\x03\xcf\xc8vB\xe4\x02\xa8\x82f\xfc\x96\x06\r\xb2~gJ\x0c\xf1pK\xb8\xfb"\xfa\x1a\xa2gpI8\x96Ac2d\x86 \x03\x96\x93\xb5\\c.\x85.#\x8bxu\xb1\xc8\xcaFb\x11o\x9bY\xa2\x15x\xb2\xbc\x11\x89@v3\xaf\x14YQa\x8a\xcc\x00\xbb\xb9O\x8e\x0b\x13\x83~\xaeG\xbf\xbc9M\x11\x03\xe0\xecw\xf0yt6\xda\xac\xb4\xc3\x05\xcb\x13H\xc4\xc8\xf9V\r\xe4\x14\x81\xcbe\\\x17\x992\x03k\xa9\x15\x9e\xa1\xa0\x81\x8e.\x02\x88\xd1\xc3 \xab\xbc\x82\xb9\xb0\r\xac4lj\xc2\xbd\nX\xc1:\x98\xd4\xcd#+\x87,\x1f\x00f\x8e\t\x82vN\xc3\xd5\xc0Cb\xeaO%\x1c\xd8\x96\x83\x16{u\xa7\x9e\xfe\xbaO\xe5R\xe8R\xf4]\x05L\xd3\xd1\x13V\x8c\xa5\x8dD\xea^n\x15\xdf\xbbC\xbfjF\x17\x01\xc4\xe8<f\x18<\x98\x0b\xdb\xd0n\xc0\xa2\xbd\xfe\x8d\xc1\x14\x01\xb6(\xc5\x1d\x91$o.p\x89\xf8#\xd1\x99\xc7\xf4R\xdb\x825\x1d\xb7{\x08\x05\xc2\xf0\xc9\xa9W\x18j\xe1\xd6\x8b\xb3+\x00\x17\xd6\x0c\xd7\xd5\xec\xcc\x0f:@\xbe\xb8\xed\x8c\xee\xae\x0e\xdd\xc3\r\xa2\xff\xb1\x15\xf0\xe7\xd3\xfa4\xdc\xb6\xeb\xad{V`\x8e\xd7X{N\xe1\x10\xc3\x81\xac\xf3\xcc\xf8\xbe`\xcd?\xe2\xfem\xc9<\xa37?\xf7S\x8e\x10\xbff\xc0\xff\xed\xabSNu\x9f\xb9=^\x87\xcf\x95w\xf9\xb5\xa8\xa0\xff\xa7(\xf7\xe2<\n\xb8/&\xfa\xff3\xd1<\xd2n\x85\xea\xbf\xd5\xba\xd9\n\xa1;\x0b\x05\xdc\x87y\xfc\xc5\xf2r-\xbe\xbe\x14F[\x17\xfb\x0ekk\t;@W\xa0+ \x14\xf0\xa7\xb53-W\xc3p\xe6N\xc3D\xac^\xec\nt\x05\xba\x02\x87\xab@\xdfa\x1d\xee\xd8tf]\x81\xae@\xa2\xc0\xbf\xd40\xb0\x19Y\x1af\xba\x00\x00\x00\x00IEND\xaeB`\x82'

**Comment by joeyHXD** [comment]
哦！应该是这边API的token没弄好，我再试试

**Comment by joeyHXD** [comment]
嗯，可以用了，是token没写对...

**Comment by CYDXDianXian** [comment]
@Jacky117  哦，对，你参照楼上，看下是不是token没写对。那个api获取的token还得去群里验证一下才能使用，不能直接用的哦~

**Comment by Jacky117** [comment]
谢谢，我根据指示修改了token，现在可以正常运行了
