### ISSUE TITLE
拉取了更新，以图绘图时报错，显示生成失败…'coroutine' object has no attribute 'content'

### ISSUE THREAD

**Issue by ryujou** [CYDXDianXian/AI_image_gen#8]

**Comment by ryujou** [comment]
![IMG_20221013_084324](https://user-images.githubusercontent.com/30500241/195473755-6af232ca-16f9-4f6b-9a73-cd238d404f06.jpg)
ai绘图指令正常

**Comment by ryujou** [comment]
回退到commit ae60ccd99e9e5ffee1043e11ed61d808146741c1功能恢复正常
![qq_pic_merged_1665622897256](https://user-images.githubusercontent.com/30500241/195475116-6e692fb6-ed23-445f-8740-56b788cd98ac.jpg)

**Comment by BlueDeer233** [comment]
此处改为[\_\_init\_\_.py 524行](https://github.com/CYDXDianXian/AI_image_gen/blob/main/__init__.py#L524)
`
image = Image.open(io.BytesIO(await (await aiorequests.get(url, timeout=20)).content))
`

**Comment by CYDXDianXian** [comment]
> 此处改为[__init__.py 524行](https://github.com/CYDXDianXian/AI_image_gen/blob/main/__init__.py#L524) `image = Image.open(io.BytesIO(await (await aiorequests.get(url, timeout=20)).content))`

感谢指出！已更新！
